/*
 * The questions somebody sceptical would actually ask, answered including the
 * ones with an uncomfortable answer. A FAQ that only contains questions the
 * project enjoys is an advertisement, and reads like one.
 */

import { Label } from "@/components/ui/Label";
import { FEE_BPS, pct } from "@/lib/economics";
import { siteConfig } from "@/lib/site-config";

const faq: { q: string; a: string }[] = [
  {
    q: "What stops somebody buying a huge bag in the last minute and taking the hour?",
    a: "Nothing stops them buying it — and it wins them nothing. The hour is paid to the longest reign inside it, so a one-minute reign scores one minute and loses to anyone who held for two. The only way to win an hour here is to actually be on top through it.",
  },
  {
    q: "The king sold everything and is still crowned. Why?",
    a: "Because the crown is taken, never handed over. A token cannot find the second-largest holder without walking an index of every holder, which no transfer can afford. So a king who dumps keeps the crown — and keeps banking seconds — until somebody with more takes it. That is an inconvenience with an obvious cure: taking it is what pays.",
  },
  {
    q: "Does the team take a cut of the hour?",
    a: `No. The fee is ${pct(FEE_BPS)} of trading volume and the whole of it goes to the hour's winner. There is no treasury address in the fee path, which is checkable rather than promised. How this project funds itself, if it ever does, is listed as an open question rather than solved with a quiet slice.`,
  },
  {
    q: "What happens in an hour nobody plays?",
    a: "The pot rolls into the next hour instead of being stranded or swept. A quiet hour makes the next one bigger, which is the correct direction for that incentive to point.",
  },
  {
    q: "Can two whales flip the crown back and forth and ruin it?",
    a: "They can, and each flip costs them gas while the fees keep accruing to whoever ends up with the most time. A minimum margin was considered and rejected: it would let a king who is a fraction ahead sit unchallengeable for the rest of the hour, and an unchallengeable king is the one thing this game must not have.",
  },
  {
    q: "Why is the liquidity pool not the king?",
    a: "It would be, which is why the pool, the token contract and the burn address are excluded from the standings before the first block. That exclusion is on the list of things that have to be true, and it is not true yet.",
  },
  {
    q: "Can I claim an old hour I won?",
    a: "Yes, forever. Pots do not expire. An expiry is a mechanism for unclaimed money to return to whoever wrote the contract, and there is nobody here for it to return to.",
  },
  {
    q: "Is anything on this page live?",
    a: "The clock and the chain read are. The standings, the pot and the button are wired to real calls with no address behind them, and every one of them says so where the figure would be. The worked hour is generated by the same functions the chain path uses, and is marked in the canvas, on the panel and on the switch.",
  },
  {
    q: `Is ${siteConfig.ticker} an investment?`,
    a: "No. It is a game with a fee that pays out hourly, and it should be treated as money you are willing to lose. Nothing here is advice, and the regulatory reading of a token that routes fees to a holder is on the open-questions list precisely because it is not settled.",
  },
];

export function Faq() {
  return (
    <section id="faq" className="mx-auto max-w-6xl px-4 py-20 sm:px-6 sm:py-28">
      <Label>[04] Questions</Label>
      <h2 className="type-head mt-4 max-w-[20ch] text-ink">
        Including the ones with an awkward answer.
      </h2>

      <dl className="mt-10 border-t border-rule">
        {faq.map((item) => (
          <div
            key={item.q}
            className="grid gap-2 border-b border-rule py-6 sm:grid-cols-[1fr_1.35fr] sm:gap-10"
          >
            <dt className="type-sub text-ink">{item.q}</dt>
            <dd className="type-body text-ink-soft">{item.a}</dd>
          </div>
        ))}
      </dl>
    </section>
  );
}
